/* ACCIONES: NOTAS Y EDITOR ENRIQUECIDO */
const COLORES_NOTA=['#FFF7DF','#FFE2DB','#F8E1EB','#E2F1E7','#DCEAF8','#EEE7FA','#F3EEE5','#FFFFFF'];
let _notaEditando=null;

function limpiarHTMLNota(html){
  const doc=new DOMParser().parseFromString(`<div>${html||''}</div>`,'text/html'), permitidos=new Set(['DIV','P','BR','B','STRONG','I','EM','U','S','H1','H2','H3','UL','OL','LI','BLOCKQUOTE','A','IMG','LABEL','INPUT','SPAN']);
  [...doc.body.querySelectorAll('*')].forEach(el=>{
    if(!permitidos.has(el.tagName)){el.replaceWith(...el.childNodes);return;}
    [...el.attributes].forEach(a=>{if(!['href','target','rel','src','alt','data-note-ref','type','checked','style','class'].includes(a.name))el.removeAttribute(a.name);});
    if(el.tagName==='A'){const h=el.getAttribute('href')||'';if(!/^https?:\/\//i.test(h))el.removeAttribute('href');else{el.target='_blank';el.rel='noopener';}}
    if(el.tagName==='IMG'&&!/^data:image\//.test(el.getAttribute('src')||'')&&!el.dataset.noteRef)el.remove();
    if(el.tagName==='INPUT')el.type='checkbox';
  });
  return doc.body.firstElementChild?.innerHTML||'';
}
function cmdNota(cmd,val=null){document.execCommand(cmd,false,val);$('#notaEditor')?.focus();}
function bloqueNota(tag){cmdNota('formatBlock',tag);}
function enlaceNota(){let u=prompt('Pega el enlace');if(!u)return;if(!/^https?:\/\//i.test(u))u='https://'+u;cmdNota('createLink',u);}
function checklistNota(){cmdNota('insertHTML','<div class="nota-check"><label><input type="checkbox"> <span>Elemento de checklist</span></label></div><div><br></div>');}
function colorTextoNota(){const c=$('#notaResaltado')?.value||'#fff09a';cmdNota('hiliteColor',c);}

async function insertarImagenNota(input){
  const file=input.files?.[0];if(!file)return;const ref=await guardarArchivo(file);if(!ref)return;const url=await urlVisible(ref)||ref;
  cmdNota('insertHTML',`<p><img src="${esc(url)}" data-note-ref="${esc(ref)}" alt="${esc(file.name)}"></p><p><br></p>`);input.value='';
}
async function hidratarImagenesNota(root=document){for(const img of root.querySelectorAll('img[data-note-ref]')){const u=await urlVisible(img.dataset.noteRef);if(u)img.src=u;}}

function editorNotaHTML(n={}){return `<div class="nota-editor-shell" style="--editor-color:${esc(n.color||'#FFF7DF')}">
  <div class="nota-meta"><input id="notaTitulo" class="nota-titulo-input" placeholder="Título de la nota" value="${esc(n.titulo||'')}"><select id="notaCarpeta"><option value="">Sin carpeta</option>${S.notas_carpetas.map(f=>`<option value="${f.id}" ${n.carpeta_id===f.id?'selected':''}>${esc(f.nombre)}</option>`).join('')}</select></div>
  <div class="nota-toolbar" role="toolbar"><button onclick="bloqueNota('h1')">Título</button><button onclick="bloqueNota('h2')">Subtítulo</button><button onclick="bloqueNota('p')">Texto</button><i></i><button onclick="cmdNota('bold')"><b>B</b></button><button onclick="cmdNota('underline')"><u>U</u></button><button onclick="cmdNota('italic')"><em>I</em></button><button onclick="cmdNota('insertUnorderedList')">• Lista</button><button onclick="cmdNota('insertOrderedList')">1. Lista</button><button onclick="checklistNota()">☑ Checklist</button><button onclick="enlaceNota()">🔗 Enlace</button><label class="nota-tool-file">🖼 Imagen<input type="file" accept="image/*" onchange="insertarImagenNota(this)"></label><label class="nota-tool-color">Resaltar <input id="notaResaltado" type="color" value="#fff09a" onchange="colorTextoNota()"></label></div>
  <div id="notaEditor" class="nota-editor" contenteditable="true" data-placeholder="Empieza a escribir…">${n.contenido||''}</div>
  <div class="nota-editor-opciones"><div><label>Etiquetas</label><input id="notaEtiquetas" placeholder="Ej. urgente, cliente, idea" value="${esc((n.etiquetas||[]).join(', '))}"></div><div><label>Color de fondo</label><div class="nota-paleta">${COLORES_NOTA.map(c=>`<button style="--c:${c}" class="${(n.color||'#FFF7DF')===c?'activo':''}" onclick="seleccionarColorNota('${c}',this)"></button>`).join('')}</div></div><label class="f-check"><input id="notaAnclada" type="checkbox" ${n.anclada?'checked':''}> 📌 Mantener anclada</label></div>
  </div>`;}

function editarNota(id=null){const n=id?S.notas.find(x=>x.id===id):null;_notaEditando=n;openModal(`<div class="modal-h"><h3>${n?'Editar nota':'Nueva nota'}</h3><button class="btn sm" onclick="closeModal()">✕</button></div><div class="modal-b">${editorNotaHTML(n||{})}</div><div class="modal-f">${n?`<button class="btn dgr" onclick="eliminarNota('${n.id}')">Eliminar</button>`:''}<button class="btn" onclick="closeModal()">Cancelar</button><button class="btn pri" onclick="guardarNota(${n?`'${n.id}'`:'null'})">Guardar nota</button></div>`,'modal-nota');requestAnimationFrame(()=>{hidratarImagenesNota($('#notaEditor'));$('#notaEditor')?.focus();});}
function seleccionarColorNota(c,b){document.querySelectorAll('.nota-paleta button').forEach(x=>x.classList.remove('activo'));b.classList.add('activo');b.closest('.nota-editor-shell').style.setProperty('--editor-color',c);b.closest('.nota-editor-shell').dataset.color=c;}
async function guardarNota(id=null){const titulo=$('#notaTitulo').value.trim()||'Sin título',shell=document.querySelector('.nota-editor-shell');const fila={titulo,contenido:limpiarHTMLNota($('#notaEditor').innerHTML),carpeta_id:$('#notaCarpeta').value||null,color:shell.dataset.color||_notaEditando?.color||'#FFF7DF',etiquetas:[...new Set($('#notaEtiquetas').value.split(',').map(x=>x.trim()).filter(Boolean))],anclada:$('#notaAnclada').checked};const r=id?await db.update('notas',id,fila):await db.insert('notas',fila);if(!r)return;closeModal();render();toast(id?'Nota actualizada ✓':'Nota creada ✓');}
async function anclarNota(id){const n=S.notas.find(x=>x.id===id);if(!n)return;await db.update('notas',id,{anclada:!n.anclada});render();}

function verNota(id){const n=S.notas.find(x=>x.id===id);if(!n)return;const f=carpetaNota(n.carpeta_id);openModal(`<div class="modal-h"><div><h3>${esc(n.titulo)}</h3><small>${f?'📁 '+esc(f.nombre)+' · ':''}${notaFecha(n)}</small></div><button class="btn sm" onclick="closeModal();editarNota('${id}')">✎ Editar</button><button class="btn sm" onclick="closeModal()">✕</button></div><div class="modal-b"><article class="nota-lectura" style="--nota-color:${esc(n.color)}"><div id="notaLecturaContenido">${limpiarHTMLNota(n.contenido)}</div><footer>${(n.etiquetas||[]).map(t=>`<span>#${esc(t)}</span>`).join('')}</footer></article></div><div class="modal-f nota-acciones"><button class="btn" onclick="compartirNota('${id}')">↗ Compartir</button><button class="btn" onclick="descargarNotaDoc('${id}')">⬇ Documento</button><button class="btn" onclick="descargarNotaPNG('${id}')">▧ Imagen</button><button class="btn" onclick="recordarNota('${id}')">🔔 Recordatorio</button><button class="btn pri" onclick="notaATarea('${id}')">✓ Convertir en tarea</button></div>`,'modal-nota');requestAnimationFrame(()=>{hidratarImagenesNota($('#modal'));activarChecklistNota('${id}');});}

function activarChecklistNota(id){const box=$('#notaLecturaContenido');if(!box)return;box.querySelectorAll('input[type="checkbox"]').forEach(input=>input.onchange=async()=>{const n=S.notas.find(x=>x.id===id);if(!n)return;input.toggleAttribute('checked',input.checked);n.contenido=limpiarHTMLNota(box.innerHTML);await db.update('notas',id,{contenido:n.contenido});toast('Checklist actualizado');});}

function eliminarNota(id){const n=S.notas.find(x=>x.id===id);confirmarPeligro('¿Eliminar esta nota?',`Se eliminará “${n?.titulo||''}”.`,async()=>{const d=document.createElement('div');d.innerHTML=n?.contenido||'';for(const img of d.querySelectorAll('img[data-note-ref]'))await borrarArchivo(img.dataset.noteRef);await db.remove('notas',id);closeModal();render();toast('Nota eliminada');});}
function modalCarpetaNota(){openModal(formModal('Nueva carpeta',`<div><label>Nombre</label><input id="nfNombre" placeholder="Ej. Reuniones o Ideas"></div><div><label>Color</label><input id="nfColor" type="color" value="#D9A03A"></div>`,'guardarCarpetaNota()','Crear carpeta'));}
async function guardarCarpetaNota(){const nombre=$('#nfNombre').value.trim();if(!nombre){toast('Escribe el nombre');return;}await db.insert('notas_carpetas',{nombre,color:$('#nfColor').value});closeModal();render();toast('Carpeta creada');}

function notaATarea(id){const n=S.notas.find(x=>x.id===id);if(!n)return;closeModal();modalTarea();requestAnimationFrame(()=>{$('#mT').value=n.titulo;$('#mN').value=notaTexto(n.contenido);});}
function recordarNota(id){const n=S.notas.find(x=>x.id===id);openModal(formModal('Crear recordatorio',`<p>Recibirás el aviso en NEXA y aparecerá en el calendario.</p><div class="f2"><div><label>Fecha</label><input id="nrFecha" type="date" value="${hoyISO()}"></div><div><label>Hora</label><input id="nrHora" type="time" value="09:00"></div></div><div><label>Avisarme con anticipación</label><select id="nrAviso"><option value="0">El mismo día</option><option value="1" selected>1 día antes</option><option value="3">3 días antes</option><option value="7">1 semana antes</option></select></div>`,`guardarRecordatorioNota('${id}')`,'Crear recordatorio'));}
async function guardarRecordatorioNota(id){const n=S.notas.find(x=>x.id===id),fecha=$('#nrFecha').value,hora=$('#nrHora').value;if(!fecha)return toast('Selecciona una fecha');await db.insert('eventos',{tipo:'recordatorio',titulo:`Nota: ${n.titulo}`,fecha,hora,aviso:+$('#nrAviso').value,notas:`Creado desde la nota ${n.titulo}`});await db.update('notas',id,{recordatorio:`${fecha}T${hora||'00:00'}:00`});closeModal();render();toast('Recordatorio creado ✓');}

async function compartirNota(id){const n=S.notas.find(x=>x.id===id),text=`${n.titulo}\n\n${notaTexto(n.contenido)}`;if(navigator.share){try{await navigator.share({title:n.titulo,text});return;}catch(e){if(e.name==='AbortError')return;}}await navigator.clipboard.writeText(text);toast('Nota copiada para compartir');}
function descargarBlob(blob,nombre){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=nombre;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function slugNota(s){return (s||'nota').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase();}
function descargarNotaDoc(id){const n=S.notas.find(x=>x.id===id);const html=`<!doctype html><meta charset="utf-8"><title>${esc(n.titulo)}</title><style>body{font:16px Arial;max-width:800px;margin:50px auto;line-height:1.6}img{max-width:100%}h1,h2{line-height:1.2}</style><h1>${esc(n.titulo)}</h1>${limpiarHTMLNota(n.contenido)}`;descargarBlob(new Blob([html],{type:'application/msword'}),slugNota(n.titulo)+'.doc');}
async function descargarNotaPNG(id){const n=S.notas.find(x=>x.id===id),texto=notaTexto(n.contenido).slice(0,1200),canvas=document.createElement('canvas');canvas.width=1200;canvas.height=1400;const ctx=canvas.getContext('2d');ctx.fillStyle=n.color||'#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#281812';ctx.font='bold 52px Arial';const wrap=(t,x,y,w,lh,font)=>{ctx.font=font;const words=t.split(/\s+/);let line='';for(const word of words){const test=line+word+' ';if(ctx.measureText(test).width>w){ctx.fillText(line,x,y);line=word+' ';y+=lh;}else line=test;}ctx.fillText(line,x,y);return y+lh;};let y=wrap(n.titulo,80,110,1040,68,'bold 52px Arial');y=wrap(texto,80,y+40,1040,42,'30px Arial');ctx.font='24px Arial';ctx.fillStyle='#725c50';ctx.fillText((n.etiquetas||[]).map(x=>'#'+x).join('  '),80,1320);canvas.toBlob(b=>descargarBlob(b,slugNota(n.titulo)+'.png'),'image/png');}
