/* ACCESOS RÁPIDOS — enlace principal visible y ficha con información adicional. */
let vistaEnlaces=localStorage.getItem('nexa_vista_enlaces')||'lista';
const detalleEnlace=d=>d?.detalles||{observaciones:'',enlaces:[]};
function setVistaEnlaces(v){vistaEnlaces=v;localStorage.setItem('nexa_vista_enlaces',v);render();}

function vEnlaces(){
  if(!S.dashboards.length)return `${pageHead('Accesos rápidos','Guarda aquí los enlaces que abres todos los días para tenerlos a un clic.','')}<div class="card" style="max-width:620px"><div class="card-b" style="padding:30px 26px"><div style="font-size:34px;opacity:.4;margin-bottom:12px">${ICO.enlaces}</div><h2 style="font-size:17px;margin-bottom:8px">¿Para qué sirve esta sección?</h2><p style="color:var(--text-2);font-size:13.5px;line-height:1.65;margin-bottom:20px">Es tu agenda de enlaces. Guarda el acceso principal y, si lo necesitas, añade observaciones y enlaces relacionados dentro de su ficha.</p><button class="btn pri" onclick="modalEnlace()">+ Guardar mi primer enlace</button></div></div>`;
  const porCliente={};S.dashboards.forEach(d=>(porCliente[d.cliente_id||'sin']||=[]).push(d));
  return `${pageHead('Accesos rápidos','Los enlaces que abres a diario, agrupados por cliente.',`<div class="vista-enlaces-toggle"><button class="btn ${vistaEnlaces==='lista'?'active':''}" onclick="setVistaEnlaces('lista')">☰ Lista</button><button class="btn ${vistaEnlaces==='cuadricula'?'active':''}" onclick="setVistaEnlaces('cuadricula')">▦ Cuadrícula</button></div><button class="btn pri" onclick="modalEnlace()">+ Nuevo enlace</button>`)}
  <div class="grid enlaces-vista-${vistaEnlaces}" style="gap:14px">${Object.entries(porCliente).map(([cid,enlaces])=>{const c=cid==='sin'?{nombre:'Sin cliente',color:'#9B8570'}:cli(cid);return `<div class="card"><div class="card-h"><h2><span class="dot" style="background:${c.color}"></span>${esc(c.nombre)}</h2><span class="chip n">${enlaces.length}</span></div><div class="card-b flush">${enlaces.map(d=>`<div class="row enlace-item" onclick="verEnlace('${d.id}')" role="button" tabindex="0" onkeydown="if(event.key==='Enter')verEnlace('${d.id}')"><div class="row-main"><div class="row-t">${esc(d.nombre)}</div><div class="row-s"><span style="font-family:var(--mono);font-size:11px;word-break:break-all">${esc(dominio(d.url))}</span></div></div><a class="btn sm pri" href="${esc(d.url)}" target="_blank" rel="noopener" onclick="event.stopPropagation()">Abrir ↗</a><div style="display:flex;gap:6px"><button class="btn sm" onclick="event.stopPropagation();copiarEnlace('${d.id}')" title="Copiar">⧉</button><button class="btn sm" onclick="event.stopPropagation();modalEnlace('${d.id}')" title="Editar">✎</button><button class="btn sm dgr" onclick="event.stopPropagation();eliminarEnlace('${d.id}')" title="Eliminar">✕</button></div></div>`).join('')}</div></div>`;}).join('')}</div><p style="font-size:12px;color:var(--text-3);margin-top:16px">Atajo: en la barra de captura escribe <code>l: https://… Nombre</code> y se guarda solo.</p>`;
}

function dominio(url){try{return new URL(url).hostname.replace(/^www\./,'');}catch{return url;}}
function urlExtraHTML(x={}){return `<div class="url-extra-form"><input data-extra="nombre" placeholder="Nombre del enlace" value="${esc(x.nombre||'')}"><input data-extra="url" type="url" placeholder="https://…" value="${esc(x.url||'')}"><button type="button" class="btn sm dgr" onclick="this.parentElement.remove()">✕</button></div>`;}
function agregarUrlEnlace(){const c=$('#enUrlsExtra');c.insertAdjacentHTML('beforeend',urlExtraHTML());c.lastElementChild?.querySelector('input')?.focus();}

function modalEnlace(id=null){const d=id?S.dashboards.find(x=>x.id===id):null,det=detalleEnlace(d);openModal(formModal(id?'Editar acceso rápido':'Nuevo acceso rápido',`<div><label>Nombre</label><input id="enNombre" placeholder="Ej. Dashboard HSEQ" value="${esc(d?.nombre||'')}"></div><div><label>URL principal</label><input id="enUrl" type="url" placeholder="https://…" value="${esc(d?.url||'')}"></div><div><label>Cliente (opcional)</label><select id="enCliente">${optsCli(d?.cliente_id)}</select></div><div><label>Observaciones o información adicional</label><textarea id="enObs" placeholder="Instrucciones de acceso, responsables, horarios, notas…">${esc(det.observaciones||'')}</textarea></div><div><div class="contactos-form-titulo"><label>Enlaces adicionales</label><button type="button" class="btn sm" onclick="agregarUrlEnlace()">+ Otro enlace</button></div><p class="campo-ayuda">Solo aparecerán dentro del detalle; la tarjeta mostrará únicamente el enlace principal.</p><div id="enUrlsExtra">${(det.enlaces||[]).map(urlExtraHTML).join('')}</div></div>`,`guardarEnlace(${id?`'${id}'`:'null'})`,id?'Guardar cambios':'Crear enlace'));}

async function guardarEnlace(id=null){const nombre=$('#enNombre').value.trim(),url=$('#enUrl').value.trim();if(!nombre)return toast('Escribe el nombre');if(!/^https?:\/\/[^\s]+$/i.test(url))return toast('Escribe una URL principal válida con https://');const enlaces=[...document.querySelectorAll('.url-extra-form')].map(x=>({nombre:x.querySelector('[data-extra="nombre"]').value.trim(),url:x.querySelector('[data-extra="url"]').value.trim()})).filter(x=>x.nombre||x.url);if(enlaces.some(x=>!x.nombre||!/^https?:\/\/[^\s]+$/i.test(x.url)))return toast('Completa el nombre y una URL válida en cada enlace adicional');const fila={nombre,url,cliente_id:$('#enCliente').value||null,detalles:{observaciones:$('#enObs').value.trim(),enlaces}};if(id)await db.update('dashboards',id,fila);else await db.insert('dashboards',fila);closeModal();render();toast(id?'Acceso actualizado':'Acceso creado');}

function verEnlace(id){const d=S.dashboards.find(x=>x.id===id);if(!d)return;const det=detalleEnlace(d),c=d.cliente_id?cli(d.cliente_id):null;openModal(`<div class="modal-h"><div style="min-width:0;flex:1"><h3>${esc(d.nombre)}</h3><small style="color:var(--text-3)">${c?esc(c.nombre):'Sin cliente'}</small></div><button class="btn sm" onclick="closeModal();modalEnlace('${id}')">✎ Editar</button><button class="btn sm" onclick="closeModal()">✕</button></div><div class="modal-b enlace-detalle"><section><div class="tf-tit"><span>Enlace principal</span></div><a class="enlace-principal" href="${esc(d.url)}" target="_blank" rel="noopener"><span><strong>${esc(d.nombre)}</strong><small>${esc(d.url)}</small></span><b>Abrir ↗</b></a></section>${det.observaciones?`<section><div class="tf-tit"><span>Observaciones</span></div><div class="tf-notas texto-pre">${esc(det.observaciones)}</div></section>`:''}${(det.enlaces||[]).length?`<section><div class="tf-tit"><span>Enlaces adicionales</span><span class="chip n">${det.enlaces.length}</span></div><div class="enlaces-adicionales">${det.enlaces.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener"><span><strong>${esc(x.nombre)}</strong><small>${esc(dominio(x.url))}</small></span><b>↗</b></a>`).join('')}</div></section>`:''}</div><div class="modal-f"><button class="btn" onclick="closeModal()">Cerrar</button><a class="btn pri" href="${esc(d.url)}" target="_blank" rel="noopener">Abrir principal ↗</a></div>`,'modal-cliente');}

async function copiarEnlace(id){const d=S.dashboards.find(x=>x.id===id);await navigator.clipboard.writeText(d.url);toast('Enlace copiado');}
function eliminarEnlace(id){const d=S.dashboards.find(x=>x.id===id);confirmarPeligro('¿Eliminar este acceso?',`Se eliminará "${d.nombre}".`,async()=>{await db.remove('dashboards',id);render();toast('Acceso eliminado');});}
